### ISSUE TITLE
Repo Name

### ISSUE THREAD

**Issue by cron410** [jim-olsen/StarlinkRemote#1]
Seems the name is already used by an older remote-start feature on Subarus. I seriously doubt anyone is going to take issue with it, but the name makes it very hard to find with general internet searches. 

Ref: https://www.subaru.com/vehicle-info/subaru-starlink.html

**Comment by jim-olsen** [comment]
Well starlink is kind of in use by elon musk, so not sure what I can do about that :-).  Never realized Subaru already used that name...

**Comment by cron410** [comment]
There was some alarm system equipment that used it too years ago. Oh well, looking forward to more cool stuff from this project.
